### Test ShowOpeningHandler - Success
GET http://localhost:8080/api/v1/opening?id=9
Authorization: Bearer valid-token

### Test ListOpeningsHandler - Success
GET http://localhost:8080/api/v1/openings
Authorization: Bearer valid-token

### Test CreateOpeningHandler - Success
POST http://localhost:8080/api/v1/opening
Content-Type: application/json
Authorization: Bearer valid-token

{  
    "role": "Application Developer",
    "company": "McDonalds",
    "location": "Silver Spring, MD",
    "type_of_employment": "Part-time",
    "salary": 63000,
    "company_logo_url": "https://www.mcd.com/en-us/",
    "description": "McDonalds is looking for a Software Engineer to join their team in Silver Spring, MD.",
    "link": "https://www.mcd.com/en-us/"
}

### Test UpdateOpeningHandler - Success
PUT http://localhost:8080/api/v1/opening?id=12
Content-Type: application/json
Authorization: Bearer valid-token

{
    "role":"Associate Developer"
}

### Test DeleteOpeningHandler - Success
DELETE http://localhost:8080/api/v1/opening?id=12
Authorization: Bearer valid-token

### Test SubscribeHandler - Success
POST http://localhost:8080/api/v1/newsletter/subscribe
Content-Type: application/json
Authorization: Bearer valid-token

{
    "user_id": 1232,
    "email": "user@example.com"
}

### Test UnsubscribeHandler - Success
DELETE http://localhost:8080/api/v1/resume/1
Authorization: Bearer

### Test GoogleAuthHandler - Success
GET http://localhost:8080/api/v1/auth/google